version: "3.4"

services:
  db:
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER_FILE: "/run/secrets/postgres-user"
      POSTGRES_PASSWORD_FILE: "/run/secrets/postgres-password"
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./db/secrets/:/run/secrets

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: michael@icefoganalytics.com
      PGADMIN_DEFAULT_PASSWORD: testing123
    ports:
      - "8111:80"
    volumes:
      - my-data:/var/lib/pgadmin

  email:
    image: marcopas/docker-mailslurper
    ports:
      - 2500:2500
      - 8081:8080
      - 8085:8085

volumes:
  pg-data:
  my-data:
